# Generated by Django 5.2 on 2025-04-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_generatedconfig_bookmark_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedconfig',
            name='fine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedconfig',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
