# Generated by Django 5.2 on 2025-04-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_generatedconfig_fine_name_generatedconfig_mime_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedconfig',
            old_name='fine_name',
            new_name='finename',
        ),
    ]
